// <auto-generated />
using System;
using HavenWellness.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HavenWellness.Migrations
{
    [DbContext(typeof(WellnessContext))]
    [Migration("20251020165128_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("HavenWellness.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A supportive community for students managing chronic health conditions",
                            GroupName = "Chronic Illness Support"
                        });
                });

            modelBuilder.Entity("HavenWellness.Models.GroupMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupMessages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GroupId = 1,
                            MessageText = "Welcome to our support group! Feel free to share your experiences.",
                            Timestamp = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            GroupId = 1,
                            MessageText = "Remember to track your symptoms daily. It really helps identify patterns.",
                            Timestamp = new DateTime(2025, 1, 16, 14, 30, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("HavenWellness.Models.SymptomDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("PainLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SymptomEntryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SymptomEntryId");

                    b.ToTable("SymptomDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Headache",
                            Notes = "Started in the morning, worsened throughout the day",
                            PainLevel = 6,
                            SymptomEntryId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fatigue",
                            Notes = "Very tired, had to take multiple breaks",
                            PainLevel = 8,
                            SymptomEntryId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Headache",
                            Notes = "Much better today, mild discomfort",
                            PainLevel = 4,
                            SymptomEntryId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Nausea",
                            Notes = "Slight nausea after lunch",
                            PainLevel = 3,
                            SymptomEntryId = 2
                        });
                });

            modelBuilder.Entity("HavenWellness.Models.SymptomEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SymptomEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = "2025-01-15",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = "2025-01-16",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("HavenWellness.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateJoined = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "demo@example.com",
                            Name = "Demo User",
                            PasswordHash = "hashed_password_demo"
                        });
                });

            modelBuilder.Entity("HavenWellness.Models.UserGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "GroupId")
                        .IsUnique();

                    b.ToTable("UserGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GroupId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("HavenWellness.Models.GroupMessage", b =>
                {
                    b.HasOne("HavenWellness.Models.Group", "Group")
                        .WithMany("GroupMessages")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HavenWellness.Models.User", "User")
                        .WithMany("GroupMessages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HavenWellness.Models.SymptomDetail", b =>
                {
                    b.HasOne("HavenWellness.Models.SymptomEntry", "SymptomEntry")
                        .WithMany("SymptomDetails")
                        .HasForeignKey("SymptomEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SymptomEntry");
                });

            modelBuilder.Entity("HavenWellness.Models.SymptomEntry", b =>
                {
                    b.HasOne("HavenWellness.Models.User", "User")
                        .WithMany("SymptomEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HavenWellness.Models.UserGroup", b =>
                {
                    b.HasOne("HavenWellness.Models.Group", "Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HavenWellness.Models.User", "User")
                        .WithMany("UserGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HavenWellness.Models.Group", b =>
                {
                    b.Navigation("GroupMessages");

                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("HavenWellness.Models.SymptomEntry", b =>
                {
                    b.Navigation("SymptomDetails");
                });

            modelBuilder.Entity("HavenWellness.Models.User", b =>
                {
                    b.Navigation("GroupMessages");

                    b.Navigation("SymptomEntries");

                    b.Navigation("UserGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
